### ISSUE TITLE
Integrate sqlc for type-safe database access

### ISSUE THREAD

**Issue by ryuuzake** [usual-teams/cinelist#9]
### Background
The backend scaffold for the Movie Watchlist Sharing Platform is ready. The next step is to integrate sqlc for type-safe SQL-to-Go code generation, improving database access safety and maintainability.

---

### Objectives

- Integrate sqlc into the backend project (using Go and SQLite).
- Set up sqlc configuration files in the project structure.
- Add a simple SQL query to fetch all movies from the SQLite database.
- Generate the corresponding Go code using sqlc.
- Update documentation (README.md) with clear steps for running sqlc, updating queries, and testing the endpoint.

---

### Suggested Steps

1. **Add sqlc to project dependencies**
   - Update `go.mod` as needed.
   - Add sqlc installation and usage to README.

2. **Create sqlc configuration**
   - Place `sqlc.yaml` or `sqlc.json` in `/backend` root.
   - Define input/output paths for SQL and generated code.
   - Example structure:
     ```yaml
     version: 2
     sql:
       - engine: sqlite
         schema: internal/database/schema.sql
         queries: internal/database/queries/
         gen:
           go:
             package: database
             out: internal/database/sqlc
     ```

3. **Write SQL schema and queries**
   - Create `schema.sql` for movie table.
   - Create `queries/movie.sql` with a `ListMovies` query:
     ```sql
     -- name: ListMovies :many
     SELECT id, title, year FROM movie;
     ```

4. **Run sqlc to generate Go code**
   - Ensure generated code appears in `internal/database/sqlc`.

5. **Update documentation**
   - Add integration instructions, command examples, and troubleshooting notes to README.md.

---

### Acceptance Criteria

- sqlc is integrated and working with SQLite in the backend project.
- Documentation is updated for both developers and reviewers.

---

### Reference

- [sqlc documentation](https://docs.sqlc.dev/)
- See project README for directory structure and setup context.
